spring:
  datasource:
    url : jdbc:mysql://192.168.200.18:3306/zentao?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
    username : zentao
    password : 123456
    driver-class-name : com.mysql.jdbc.Driver

  freemarker:
    checkTemplateLocation : false
    cache: false
    setting :
      template_update_delay : 0
      default_encoding : UTF-8

  data:
    mongodb:
      host: 120.26.72.219
      port: 27017
      username: traderwork
      password: abc123
      database: traderwork
      authenticationDatabase: traderwork
---
spring:
    profiles: dev
name: Dev

---
spring:
    profiles: prod
name: Prod